# Configuration for Viral Reel Bot
# Rename this file to config.py and fill in your credentials

# GOOGLE CREDENTIALS (for Gemini)
GOOGLE_EMAIL = "YOUR_GOOGLE_EMAIL"
GOOGLE_PASSWORD = "YOUR_GOOGLE_PASSWORD"

# CHATGPT CREDENTIALS
CHATGPT_EMAIL = "YOUR_CHATGPT_EMAIL"
CHATGPT_PASSWORD = "YOUR_CHATGPT_PASSWORD"

# INSTAGRAM CREDENTIALS
INSTAGRAM_USERNAME = "YOUR_INSTAGRAM_USERNAME"
INSTAGRAM_PASSWORD = "YOUR_INSTAGRAM_PASSWORD"

# Optional
OPENAI_API_KEY = ""
GEMINI_API_KEY = ""
